name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Install 
      run: |
        rustup target add x86_64-unknown-linux-gnu 
        cargo install cargo-lambda
    - name: Build
      run: cargo lambda build --release --target x86_64-unknown-linux-gnu
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: bootstrap
        path: ./target/lambda/gauss_lambda/bootstrap.zip
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: bootstrap
    - name: Deploy
      run: |
        aws cloudformation package --template-file template.yml \
                          --s3-bucket rust-deployment \
                          --output-template-file out.yml
        aws cloudformation deploy --template-file out.yml \
                          --stack-name my-stack \
                          --capabilities CAPABILITY_IAM
